### ISSUE TITLE
Techel.apply_operations how to catch a failure

### ISSUE THREAD

**Issue by asbjornenge** [OCamlPro/techelson#12]
Hi!

I would like to verify that a particular contract call fails. Is there a way to "catch" the failure of `Techel.apply_operations` - and verify the failure message?

Thanks 😄

**Comment by AdrienChampion** [comment]
Hey!

By your message you seem to be using Techelson with Liquidity. If you look at the [external contract example Section] in my blog post, you will see that I use `Techel.must_fail` which almost does what you want.

At liquidity level, you currently cannot use this extension to catch error messages. But if you look at how the extensions are defined,

```ocaml
external must_fail :
    [%stack: operation] -> [%stack: operation]
    = "{ NONE string ; MUST_FAIL string }"
```

The weird `NONE string` that's pushed on the stack is exactly what you want: it is the error message of the failure. I'm going to update the post to allow users to specify the error message and pass it to `must_fail`.

In the mean time, you can rewrite the definition of `must_fail` to

```ocaml
external must_fail :
    [%stack: string] -> [%stack: operation] -> [%stack: operation]
    = "{ DIP { SOME } ; MUST_FAIL string }"
```

Then you can use it as `must_fail <error_string> <operation>`. This will work iff `<operation>` fails with message `<error_string>`.

I'll notify you once the Liquidity blog post is updated.

Thank you!

[external contract example Section]: https://adrienchampion.github.io/blog/tezos/techelson/with_liquidity/external.html#testing-multi-and-failing-to-do-so (Liquidity + Techelson blog post)

**Comment by AdrienChampion** [comment]
I just updated [the blog post](https://adrienchampion.github.io/blog/tezos/techelson/with_liquidity/index.html). Note that the extension file [has changed](https://adrienchampion.github.io/blog/tezos/techelson/with_liquidity/extensions.html) to update `must_fail`.

The discussion in [External Contract Example](https://adrienchampion.github.io/blog/tezos/techelson/with_liquidity/external.html) about `must_fail` has been updated to show how to catch the error message of a failure.

Let me know if this works for you, and if it does, would you mind closing this issue?

**Comment by asbjornenge** [comment]
Fantastic 🎉 Works perfectly! Thanks a bunch 🙌

**Comment by AdrienChampion** [comment]
Glad it works for you, let me know if you have more questions/problems!
