### ISSUE TITLE
Getting error on Test16

### ISSUE THREAD

**Issue by rlkelly** [OCamlPro/techelson#9]
When I run test16 I get:

$ make test
running tests for "rsc/tests/test16"
     okay/Test16Test2.techel                   ...error /(T_T)\
        exit code: 127 (expected 0)
        command: "./bin/techelson --contract rsc/tests/test16/contracts/test16.liq.tz -- rsc/tests/test16/okay/Test16Test2.techel"
make: *** [bin-test] Error 2

**Comment by AdrienChampion** [comment]
Hi there, thank you for your feedback!

What you're reporting is strange. All tests [pass on the latest commit](https://travis-ci.org/OCamlPro/techelson/builds/501947023#L833), so I'm not sure what's going on. The test script runs all tests with a timeout of 2 seconds, and `make test` says the exit code is 127, so it looks like a timeout. Which is strange unless you run on a very old computer or a VM with limited resources.

After checking that you have the latest commit, you can try running the command reported in `make test`'s trace yourself: `./bin/techelson --contract rsc/tests/test16/contracts/test16.liq.tz -- rsc/tests/test16/okay/Test16Test2.techel`. See what happens. If it's successful but takes more than 2 seconds, let me know and we'll raise the timeout in the test script.
Otherwise, can you tell me what system / VM configuration you're running Techelson on?

**Comment by rlkelly** [comment]
I'm running on an older macbook, but it fails in less than 2 seconds.  The issue must be with my computer somwhere.  When I run the single test I get:


```
$ ./bin/techelson --contract rsc/tests/test16/contracts/test16.liq.tz -- rsc/tests/test16/okay/Test16Test2.techel
Running test `Test16Test2`

running test script...
   timestamp: 1970-01-01 00:00:00 +00:00

applying operation CREATE[uid:0] (@address[1], "sha256:", None, true, true, 809490134807070utz) "Test16"
   timestamp: 1970-01-01 00:00:00 +00:00
   live contracts: none
=> live contracts: Test16 (809490134807070utz) address[1]

running test script...
   timestamp: 1970-01-01 00:00:00 +00:00

applying operation TRANSFER[uid:1] address[0]@Test16Test2 -> address[1] 237190479159247utz 0
   timestamp: 1970-01-01 00:00:00 +00:00
   live contracts: Test16 (809490134807070utz) address[1]

running TRANSFER[uid:1] address[0]@Test16Test2 -> address[1] 237190479159247utz 0
   timestamp: 1970-01-01 00:00:00 +00:00
=> live contracts: Test16 (1046680613966317utz) address[1]

running test script...
   timestamp: 1970-01-01 00:00:00 +00:00

applying operation TRANSFER[uid:2] address[0]@Test16Test2 -> address[1] 369101476138376utz -252
   timestamp: 1970-01-01 00:00:00 +00:00
   live contracts: Test16 (1046680613966317utz) address[1]

running TRANSFER[uid:2] address[0]@Test16Test2 -> address[1] 369101476138376utz -252
   timestamp: 1970-01-01 00:00:00 +00:00
=> live contracts: Test16 (1415782090104693utz) address[1]

running test script...
   timestamp: 1970-01-01 00:00:00 +00:00

Done running test `Test16Test2`
```

**Comment by AdrienChampion** [comment]
Well, the test passes... I don't know what's going on. Can you run

`timeout 2 ./bin/techelson --contract rsc/tests/test16/contracts/test16.liq.tz -- rsc/tests/test16/okay/Test16Test2.techel`

followed immediately by

`echo "$?"`

and let me know what you get?

**Comment by iguerNL** [comment]
May the issue be related to the implementation of the `timeout` command on Mac OS ?

**Comment by rlkelly** [comment]
yep, that's the issue.  I added

`alias timeout=gtimeout`

and it works.

**Comment by rlkelly** [comment]
this requires mac users to run
`brew install coreutils`

**Comment by AdrienChampion** [comment]
What version of macos are you running?

I compile and run on macos, I use macos's `timeout` (but also have `gtimeout` installed) and it works fine.

**Comment by rlkelly** [comment]
I have mojave.

**Comment by AdrienChampion** [comment]
It's not that old, that's strange. I guess it doesn't matter if it's fixed, but if you want to get to the bottom of this let me know what `timeout 2 ./bin/techelson --contract rsc/tests/test16/contracts/test16.liq.tz -- rsc/tests/test16/okay/Test16Test2.techel` followed by `echo "$?"` gives you.

**Comment by rlkelly** [comment]
it works correctly now.

```...
running test script...
   timestamp: 1970-01-01 00:00:00 +00:00

Done running test `Test16Test2`
```

**Comment by AdrienChampion** [comment]
Okay, I guess everything is fine, can we close this issue?

**Comment by rlkelly** [comment]
yes, thank you

**Comment by AdrienChampion** [comment]
Don't mention it, and thank you for your interest in techelson and your feedback :D
